/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExpiryRouteImport } from './routes/_authenticated/expiry'
import { Route as AuthenticatedIssueRouteImport } from './routes/_authenticated/issue'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory.index'
import { Route as AuthenticatedInventoryUnitIdRouteImport } from './routes/_authenticated/inventory.$unitId'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests.index'
import { Route as AuthenticatedRequestsRequestIdRouteImport } from './routes/_authenticated/requests.$requestId'
import { Route as AuthenticatedRequestsNewRouteImport } from './routes/_authenticated/requests.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/_authenticated/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExpiryRoute = AuthenticatedExpiryRouteImport.update({
  id: '/_authenticated/expiry',
  path: '/expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIssueRoute = AuthenticatedIssueRouteImport.update({
  id: '/_authenticated/issue',
  path: '/issue',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/_authenticated/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/_authenticated/inventory/',
    path: '/inventory/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInventoryUnitIdRoute =
  AuthenticatedInventoryUnitIdRouteImport.update({
    id: '/_authenticated/inventory/$unitId',
    path: '/inventory/$unitId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/_authenticated/requests/',
    path: '/requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRequestsRequestIdRoute =
  AuthenticatedRequestsRequestIdRouteImport.update({
    id: '/_authenticated/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRequestsNewRoute =
  AuthenticatedRequestsNewRouteImport.update({
    id: '/_authenticated/requests/new',
    path: '/requests/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expiry': typeof AuthenticatedExpiryRoute
  '/issue': typeof AuthenticatedIssueRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/inventory/$unitId': typeof AuthenticatedInventoryUnitIdRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expiry': typeof AuthenticatedExpiryRoute
  '/issue': typeof AuthenticatedIssueRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/inventory/$unitId': typeof AuthenticatedInventoryUnitIdRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expiry': typeof AuthenticatedExpiryRoute
  '/_authenticated/issue': typeof AuthenticatedIssueRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/inventory/$unitId': typeof AuthenticatedInventoryUnitIdRoute
  '/_authenticated/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/_authenticated/requests/new': typeof AuthenticatedRequestsNewRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/dashboard'
    | '/expiry'
    | '/issue'
    | '/reports'
    | '/settings'
    | '/inventory/$unitId'
    | '/requests/$requestId'
    | '/requests/new'
    | '/inventory/'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/dashboard'
    | '/expiry'
    | '/issue'
    | '/reports'
    | '/settings'
    | '/inventory/$unitId'
    | '/requests/$requestId'
    | '/requests/new'
    | '/inventory'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/approvals'
    | '/_authenticated/dashboard'
    | '/_authenticated/expiry'
    | '/_authenticated/issue'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/inventory/$unitId'
    | '/_authenticated/requests/$requestId'
    | '/_authenticated/requests/new'
    | '/_authenticated/inventory/'
    | '/_authenticated/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpiryRoute: typeof AuthenticatedExpiryRoute
  AuthenticatedIssueRoute: typeof AuthenticatedIssueRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedInventoryUnitIdRoute: typeof AuthenticatedInventoryUnitIdRoute
  AuthenticatedRequestsRequestIdRoute: typeof AuthenticatedRequestsRequestIdRoute
  AuthenticatedRequestsNewRoute: typeof AuthenticatedRequestsNewRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/expiry': {
      id: '/_authenticated/expiry'
      path: '/expiry'
      fullPath: '/expiry'
      preLoaderRoute: typeof AuthenticatedExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/issue': {
      id: '/_authenticated/issue'
      path: '/issue'
      fullPath: '/issue'
      preLoaderRoute: typeof AuthenticatedIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inventory/$unitId': {
      id: '/_authenticated/inventory/$unitId'
      path: '/inventory/$unitId'
      fullPath: '/inventory/$unitId'
      preLoaderRoute: typeof AuthenticatedInventoryUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/requests/$requestId': {
      id: '/_authenticated/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/requests/new': {
      id: '/_authenticated/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AuthenticatedRequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpiryRoute: AuthenticatedExpiryRoute,
  AuthenticatedIssueRoute: AuthenticatedIssueRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedInventoryUnitIdRoute: AuthenticatedInventoryUnitIdRoute,
  AuthenticatedRequestsRequestIdRoute: AuthenticatedRequestsRequestIdRoute,
  AuthenticatedRequestsNewRoute: AuthenticatedRequestsNewRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
